services:

  questkeeper_aspnet_api:
    container_name: questkeeper_aspnet_api
    restart: always
    build:
      context: .
      dockerfile: applications/RPGTableHelper.WebApi/Dockerfile
    ports:
      - "7777:8080"
      - "7778:5131"
      - "7779:7172"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /mnt/user/appdata/rpgtablehelper_questkeeper:/app/database

  questkeeper_cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: questkeeper_cloudflare_tunnel
    depends_on:
      - questkeeper_aspnet_api
    restart: always
    command: tunnel --no-autoupdate run --url http://questkeeper_aspnet_api:8080

volumes:
  questkeeper_sqlitedb:
