import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:rpg_table_helper/constants.dart';
import 'package:rpg_table_helper/helpers/icons_helper.dart';
import 'package:rpg_table_helper/services/dependency_provider.dart';

import '../test_configuration.dart';

var allIconNames = [
  "anchor",
  "biohazard",
  "bolt",
  "bolt-lightning",
  "bomb",
  "bone",
  "book",
  "book-open",
  "broom",
  "burst",
  "campground",
  "carrot",
  "cat",
  "chess-rook",
  "chess-king",
  "chess-queen",
  "chess-knight",
  "circle-radiation",
  "clock",
  "cloud-bolt",
  "cloud-moon",
  "cloud-showers-heavy",
  "cloud-sun",
  "clover",
  "comment",
  "comments",
  "compass",
  "compass-drafting",
  "cow",
  "cross",
  "crosshairs",
  "crow",
  "crown",
  "dice",
  "dice-d20",
  "dice-six",
  "dog",
  "dove",
  "dragon",
  "droplet",
  "drumstick-bite",
  "dungeon",
  "earth-europe",
  "egg",
  "envelope",
  "explosion",
  "eye",
  "feather",
  "feather-pointed",
  "file",
  "fingerprint",
  "fire",
  "fire-flame-curved",
  "fish-fins",
  "flag",
  "flask",
  "frog",
  "gavel",
  "gear",
  "gears",
  "gem",
  "ghost",
  "gift",
  "glasses",
  "gun",
  "hammer",
  "hand-holding-heart",
  "hand-holding-medical",
  "hat-cowboy",
  "hat-wizard",
  "heart",
  "heart-circle-bolt",
  "helicopter",
  "hippo",
  "horse",
  "hourglass",
  "hourglass-half",
  "house-chimney",
  "house",
  "ice-cream",
  "igloo",
  "industry",
  "infinity",
  "jet-fighter",
  "jet-fighter-up",
  "key",
  "kiwi-bird",
  "landmark",
  "leaf",
  "lemon",
  "lightbulb",
  "link",
  "link-slash",
  "list",
  "list-check",
  "location-arrow",
  "location-crosshairs",
  "location-dot",
  "lock",
  "lock-open",
  "magnifying-glass",
  "map",
  "map-location-dot",
  "martini-glass",
  "medal",
  "meteor",
  "microchip",
  "microphone",
  "microphone-slash",
  "moon",
  "mortar-pestle",
  "mosque",
  "motorcycle",
  "mountain",
  "mountain-sun",
  "music",
  "otter",
  "paintbrush",
  "palette",
  "paw",
  "pen-nib",
  "people-group",
  "pepper-hot",
  "person-running",
  "person-swimming",
  "piggy-bank",
  "place-of-worship",
  "plane",
  "puzzle-piece",
  "radiation",
  "receipt",
  "robot",
  "rocket",
  "sailboat",
  "scale-balanced",
  "screwdriver-wrench",
  "seedling",
  "shield",
  "shield-halved",
  "shield-heart",
  "shoe-prints",
  "shop",
  "shrimp",
  "shuttle-space",
  "skull",
  "skull-crossbones",
  "snowflake",
  "spider",
  "star",
  "store",
  "sun",
  "tag",
  "tent",
  "tents",
  "tooth",
  "tree",
  "trophy",
  "user-shield",
  "wand-magic-sparkles",
  "wand-sparkles",
  "yin-yang",
];

void main() {
  group('AllCategoryIcons rendering', () {
    for (var i = 0; i < allIconNames.length; i++) {
      var iconNameToTest = allIconNames[i];
      testConfigurations(
        disableLocals: true,
        widgetName: 'AllCategoryIcons$i',
        useMaterialAppWrapper: true,
        screenFactory: (Locale locale) => getIconForIdentifier(
          name: iconNameToTest,
          color: darkColor,
          size: 32,
        ).$2,
        getTestConfigurations: (Widget widgetToTest) => Map.fromEntries([
          MapEntry(
            'default',
            DependencyProvider.getMockedDependecyProvider(
              child: Container(
                color: bgColor,
                child: Center(
                  child: widgetToTest,
                ),
              ),
            ),
          ),
        ]),
      );
    }
  });
}
