targets:
  $default:
    sources:
      - lib/**
      - swagger/**
      - $package$
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_json_keys: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

      chopper_generator:
        options:
          header: "// Generated code"
      swagger_dart_code_generator:
        options:
          use_inheritance: true
          input_folder: "swagger/"
          output_folder: "lib/generated/swaggen/"
          with_base_url: true
          enums_case_sensitive: false
          separate_models: true

