name: rpg_table_helper
description: "A tablet app helping with your favorite RPG table top games!"
publish_to: 'none'

version: 0.1.0+12

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.3
  timeago: ^3.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  shadow_widget: ^0.1.1
  get_it: ^7.7.0
  modal_bottom_sheet: ^3.0.0-pre
  chopper: ^8.0.1+1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  copy_with_extension: ^5.0.4
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0
  custom_lint: ^0.6.4
  json_serializable: ^6.8.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.4




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-2/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-2/Roboto-Italic.ttf
        style: italic
      - asset: assets/fonts/Roboto-2/Roboto-Bold.ttf
        style: bold

flutter_intl:
  enabled: true
