name: rpg_table_helper
description: "A tablet app helping with your favorite RPG table top games!"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  intl: any
  font_awesome_flutter: ^10.6.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  shared_preferences: ^2.2.3
  timeago: ^3.7.0
  asn1lib: ^1.5.3
  chopper: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.11
  chopper_generator: ^8.0.0


flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


flutter_intl:
  enabled: true
  main_locale: de
