name: rpg_table_helper
description: "A tablet app helping with your favorite RPG table top games!"
publish_to: 'none'

version: 0.2.0+59

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.3
  timeago: ^3.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  shadow_widget: ^0.1.1
  get_it: ^8.0.0
  modal_bottom_sheet: ^3.0.0-pre
  chopper: ^8.0.1+1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  copy_with_extension: ^5.0.4
  flutter_markdown: ^0.7.3+1
  signalr_netcore: ^1.3.9
  http: ^1.2.2
  collection: ^1.18.0
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.5
  pointycastle: ^3.9.1
  asn1lib: ^1.5.5
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0
  custom_lint: ^0.6.4
  json_serializable: ^6.8.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.4
  flutter_launcher_icons: "^0.14.1"
  chopper_generator: ^8.0.3
  swagger_dart_code_generator: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-2/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-2/Roboto-Italic.ttf
        style: italic
      - asset: assets/fonts/Roboto-2/Roboto-Bold.ttf
        style: bold

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21