# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      attestations: none
      checks: none
      contents: read
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: read
      security-events: none
      statuses: none

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.41.6

      - name: Prepare Flutter workspace
        shell: bash
        run: |
          set -euxo pipefail
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE/applications"
          ls -la "$GITHUB_WORKSPACE/applications/rpg_table_helper"
          mkdir -p "$GITHUB_WORKSPACE/applications/rpg_table_helper/build"
          ls -ld "$GITHUB_WORKSPACE/applications/rpg_table_helper/build"

      - name: Install dependencies
        working-directory: ./applications/rpg_table_helper
        run: flutter pub get

      - name: Run tests
        working-directory: ./applications/rpg_table_helper
        run: flutter test --exclude-tags golden
