# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      attestations: none
      checks: none
      contents: read
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: read
      security-events: none
      statuses: none

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.24.0

      - name: Install dependencies
        run: cd ./applications/rpg_table_helper && flutter pub get

      - name: Run tests
        run: cd ./applications/rpg_table_helper && flutter test --update-goldens
