name: .NET

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'applications/rpg_table_helper/**'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
      - 'applications/rpg_table_helper/**'

jobs:
  build:
    name: Build & Test Solution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    # - name: Pack
    #   run: dotnet pack --no-build -c Release -o out /p:VersionSuffix=${GITHUB_RUN_NUMBER}
    # - name: Upload Packages as artifacts
    #   uses: actions/upload-artifact@v3.0.0
    #   with:
    #     name: packages
    #     path: '**/*.nupkg'
    # - name: Push to nuget.org
    #   if: startsWith(github.ref, 'refs/tags/v')
    #   run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
    #   env:
    #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}